version: '3'
services:
  fastapi:
    image: fastapi
    build:
      context: .
    
    working_dir: /fastapi/application
    ports:
      - "8000:8000"
    volumes:
      - ./:/fastapi

    command: bash -c "
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

    container_name: fastapi



  prefect:
    image: fastapi
    build:
     context: .
    working_dir: /fastapi/prefect
    ports:
      - "42001:42001"

    environment:
      #- PREFECT__UI__HOST = 0.0.0.0
      PREFECT_ORION_API_HOST: 0.0.0.0
      PREFECT_ORION_ANALYTICS_ENABLED: "false"
      PREFECT_LOGGING_SERVER_LEVEL: WARNING
      PREFECT_API_URL: http://140.96.111.93:42001/api
      #PREFECT_API_URL: https://app.prefect.cloud/account/000813b1-9484-4ee3-aadd-0dcc70a0e326/workspace/6bd934c4-6a1b-494d-8b4d-f81bb8dee87b/api
      PREFECT_API_KEY : 'pnu_O7OETkJsA0bkdskXSkJvA0ZMkY60sW3tQape'

    

    volumes:
      - ./prefect:/fastapi/prefect
      - ./prefect/volumes:/root/.prefect



    command : bash -c "
      prefect orion start --port 42001"
      

    container_name: prefect_42001

 