version: '3'
services:
  fastapi:
    image: fastapi
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/fastapi
    
    command: bash -c "
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    
    container_name: fastapi
    working_dir: /fastapi



 